Revert changes to JUnitReporter
1) Jackson introduced a regression in JUnitReporter, and for
some strange reason the "classname" attribute was serialized out with
garbage characters in it.
Going back to the old version based on JAXB.
Jackson is still used everywhere else.

2) Adding JAXB dependencies to the assembly to avoid the runtime error:
SEVERE: Fail to endRun
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
        at jsystem.extensions.report.junit.JUnitReporter.toXml(JUnitReporter.java:143)
        at jsystem.extensions.report.junit.JUnitReporter.endRun(JUnitReporter.java:369)